package domain.attachment;

public enum Genre {
    ROCK,
    POP,
    RAP_AND_HIPHOP,
    EASY_LISTENING,
    HOUSE_AND_DANCE,
    INSTRUMENTAL,
    METAL,
    ALTERNATIVE,
    DUBSTEP,
    JAZZ_AND_BLUES,
    DRUM_AND_BASS,
    TRANCE,
    CHANSON,
    ETHNIC,
    ACOUSTIC_AND_VOCAL,
    REGGAE,
    CLASSICAL,
    INDIE_POP,
    SPEECH,
    ELECTROPOP_AND_DISCO,
    OTHER
}
